version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule: { interval: "weekly" }
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly" }
  # uncomment if you use Node in / or subdir:
  # - package-ecosystem: "npm"
  #   directory: "/"
  #   schedule: { interval: "weekly" }
